name: Firebase Deploy

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - uses: actions/checkout@v2
            - uses: google-github-actions/auth@v0
              with:
                  credentials_json: ${{ secrets.FIREBASE_CREDENTIALS }}
            
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16'

            - name: Install dependencies
              run: npm install
            
            - name: Build the app
              run: npm run build
            
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  site: fir-blog-ab578
                  auth: ${{ secrets.FIREBASE_TOKEN }}
                  cwd: build
                  public: build

            - name: Deploy to Firebase Hosting
              env:
                FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
              run: |
                npm install -g firebase-tools
                firebase deploy --only hosting
