name: Firebase Deploy

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: google-github-actions/auth@v0
              with:
                  credentials_json: ${{ secrets.FIREBASE_CREDENTIALS }}
            - name: Install dependencies
              run: npm install
            - name: Build the app
              run: npm run build
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  site: fir-blog-ab578
                  auth: ${{ secrets.FIREBASE_TOKEN }}
                  cwd: build
                  public: build
