# .github/workflows/firebase-hosting-push.yml
name: Deploy to Firebase Hosting on Push

on:
  push:
    branches:
      - main  # You can specify the branch you want this action to trigger on, like 'main' or 'master'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Ensure this is the correct version for your app

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build  # This will run the build command for your React app

    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@v2
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
